config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :questions do
    resources :answers, only: %i[create destroy]
    member do
      post :solve
    end
    collection do
      get :unsolved, :solved
    end
  end

  namespace :admin do
    get    '/login', to: 'sessions#new'
    post   '/login', to: 'sessions#create'
    resources :users, only: %i[index destroy]
    resources :questions, only: %i[index destroy]
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 1000 }
  validates :solved, inclusion: [true, false]
  validates :user_id, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < ApplicationController
  before_action :admin_user

  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).per(5)
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = '質問を削除しました'
    redirect_to admin_users_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :reject_not_logged_in_user, only: %i[new create edit update destroy solve]
  before_action :reject_incorrect_user, only: %i[edit update destroy solve]

  def index
    @questions = Question.eager_load(:user).order(created_at: :desc).page(params[:page]).per(5)
  end

  def solved
    @questions = Question.eager_load(:user).where(solved: true).order(created_at: :desc).page(params[:page]).per(5)
    render :index
  end

  def unsolved
    @questions = Question.eager_load(:user).where(solved: false).order(created_at: :desc).page(params[:page]).per(5)
    render :index
  end

  def new
    @question = current_user.questions.build
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      User.where.not(id: @question.user_id).find_each do |user|
        QaMailer.question_notification(@question, user).deliver_now
      end
      flash[:success] = '質問を作成しました'
      redirect_to @question
    else
      flash.now[:danger] = '質問の作成ができませんでした'
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.eager_load(:user)
    @answer = current_user.answers.build if logged_in?
  end

  def edit; end

  def update
    if @question.update(question_params)
      flash[:success] = '質問を更新しました'
      redirect_to @question
    else
      flash.now[:danger] = '質問の更新ができませんでした'
      render 'edit'
    end
  end

  def destroy
    @question.destroy
    flash[:success] = '質問を削除しました'
    redirect_to root_url
  end

  def solve
    if @question.update(solved: true)
      flash[:success] = '解決済みにしました'
      redirect_to question_path(@question)
    else
      flash.now[:danger] = '解決済みにできませんでした'
      render question_url(@question)
    end
  end

  private

  def reject_incorrect_user
    @question = current_user.questions.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>

  <%= f.label :title, "タイトル" %>
  <%= f.text_field :title %>

  <%= f.label :body, "質問内容" %>
  <%= f.text_area :body, size: "30x10" %>

  <%= f.submit yield(:button_text) %>
<% end %>

app/views/questions/edit.html.erb
<% provide(:button_text, '更新する') %>

<h1>Questions#edit</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions#index</h1>

<ul>
  <li><%= link_to "全て", root_path %></li>
</ul>
<ul>
  <li><%= link_to "未解決", unsolved_questions_path %></li>
</ul>
<ul>
  <li><%= link_to "解決", solved_questions_path %></li>
</ul>

<ul>
  <% @questions.each do |question| %>
    <li>
      <%= question.user.name %>
    </li>
    <li>
      <%= question.title %>
      <% if question.solved %>
        <span>解決済み</span>
      <% else %>
        <span>未解決</span>
      <% end %>
    </li>
    <li>
      <%= simple_format(question.body) %>
    </li>
    <li>
      <%= link_to "回答を見る", question %>
    </li>
    <% if logged_in? && current_user.id == question.user_id %>
      <li>
        <%= link_to "質問削除", question, method: :delete, data: {confirm: "質問を削除します"} %>
      </li>
    <% end %>
  <% end %>
  <%= paginate @questions %>
</ul>

app/views/questions/new.html.erb
<% provide(:button_text, '質問する') %>

<h1>Questions#new</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1>Questions#show</h1>

<ul id='question-area' >
  <li><%= @question.title %></li>

  <% if @question.solved %>
    <span>解決済み</span>
  <% else %>
    <span>未解決</span>
    <% if logged_in? && current_user.id == @question.user_id %>
      <%= button_to "解決済みにする", solve_question_path(@question), method: :post, data: {confirm: "質問を解決済みにします"} %>
    <% end %>
  <% end %>

  <li><%= simple_format(@question.body) %></li>
  <% if logged_in? && current_user.id == @question.user_id %>
    <li><%= link_to "編集", edit_question_path(@question) %></li>
    <li><%= link_to "削除", @question, method: :delete, data: {confirm: "質問を削除します"} %></li>
  <% end %>
</ul>

<h2>回答</h2>
<ul>
  <%= render @answers %>
</ul>

<% if logged_in? %>
  <%= render '/answers/form' %>
<% end %>