config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :questions do
    resources :answers, only: %i[create destroy]
    member do
      post :solve
    end
    collection do
      get :unsolved, :solved
    end
  end

  namespace :admin do
    get    '/login', to: 'sessions#new'
    post   '/login', to: 'sessions#create'
    resources :users, only: %i[index destroy]
    resources :questions, only: %i[index destroy]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :body, presence: true, length: { maximum: 1000 }
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :reject_not_logged_in_user, only: %i[create destroy]
  before_action :reject_incorrect_user, only: :destroy

  def create
    @answer = current_user.answers.build(answer_params)
    user_ids = @answer.question.answers.where.not(user_id: @answer.user_id).pluck(:user_id) + [@answer.question.user_id]
    if @answer.save
      User.where(id: user_ids).find_each do |user|
        QaMailer.answer_notification(@answer, user).deliver_now
      end
      flash[:success] = '回答しました'
      redirect_to question_path(@answer.question_id)
    else
      flash[:danger] = '回答できませんでした'
      redirect_to question_path(@answer.question_id)
    end
  end

  def destroy
    answer = Answer.find(params[:id])
    answer.destroy
    flash[:success] = '回答を削除しました'
    redirect_to question_path(answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :question_id)
  end

  def reject_incorrect_user
    answer = current_user.answers.find_by(params[:id])
    if answer.nil?
      flash[:danger] = '他のユーザの回答は編集できません'
      redirect_to question_path(Answer.find(params[:id]).question)
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<li id='answer_<%= answer.id %>'>
  <%= answer.user.name %>：<%= answer.body %>
  <% if logged_in? && current_user.id == answer.user_id %>
    <%= link_to '削除', question_answer_path(@question, answer), method: :delete, data: {confirm: "回答を削除します"}  %>
  <% end %>
</li>

app/views/answers/_form.html.erb
<%= form_with model: [@question, @answer] do |f| %>

  <%= f.hidden_field :question_id, { value: @question.id} %>

  <%= f.label :body, "回答内容" %>
  <%= f.text_area :body, size: "30x10" %>

  <%= f.submit "回答する" %>
<% end %>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>