config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :questions do
    resources :answers, only: %i[create destroy]
    member do
      post :solve
    end
    collection do
      get :unsolved, :solved
    end
  end

  namespace :admin do
    get    '/login', to: 'sessions#new'
    post   '/login', to: 'sessions#create'
    resources :users, only: %i[index destroy]
    resources :questions, only: %i[index destroy]
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_nav.html.erb
<nav>
  <%= link_to "Q & A Sample app", root_path %>
  <div>
    <ul>
    <% if logged_in? %>
      <li>
        <%= link_to "質問作成", new_question_path %>
      </li>
      <li>
        <%= link_to "ログアウト", logout_path, method: :delete %>
      </li>
      <li>
        <%= current_user.name %>
      </li>
    <% else %>
      <li>
        <%= link_to "ログイン", login_path %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QASampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>